# Generated by Django 2.2 on 2019-04-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
