# Generated by Django 2.2 on 2019-04-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20190411_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
